#ifndef MAIN_FRAME_H
#define MAIN_FRAME_H

#include <wx/wx.h>
#include <wx/clipbrd.h>
#include <string>

#include "requestdlg.h"
#include "tox-handler.h"
class ToxHandler;
class RequestDlgEvt;

#include "messagebox.h"

class MainFrame : public wxFrame
{
private:
    bool mBtnConnectedClicked{false};
    bool m_isDeleting{false};

public:
    MainFrame();
    ~MainFrame();

    enum
    {
        MAIN_FRAME = wxID_HIGHEST + 1,
        NAME_BTN,
        SEND_BTN,
        ADD_BTN
    };

public:
    //ctrls
    wxTextCtrl *m_toxIDCtrl;
    wxTextCtrl *m_nameCtrl;
    wxTextCtrl *m_messageCtrl;
    wxListBox *m_friendsBox;
    MessageBox *m_messageBox;

    //buttons
    wxButton *m_nameBtn;
    wxButton *m_sendBtn;
    wxButton *m_addBtn;

    // Event handlers
    void OnClose(wxCloseEvent &evt);
    void OnSendMessage(wxCommandEvent &evt);
    void OnChangeName(wxCommandEvent &evt);
    void OnFriendAdd(wxCommandEvent &evt);
    void OnSwitchFriend(wxCommandEvent &evt);

    // events generated by tox handler
    void OnToxID(wxCommandEvent &evt);
    void OnFriendRequest(wxCommandEvent &evt);
    void OnFriendStatusUpdate(wxCommandEvent &evt);

    void AddFrndCb(RequestDlgEvt &evt);
    void AcceptFrndCb(RequestDlgEvt &evt);

    ToxHandler *mTHandler{nullptr};
    wxCriticalSection mTHandlerCS;

    wxDECLARE_EVENT_TABLE();
};

#endif